services:
  mariadb:
    image: ${MARIADB_IMAGE}
    container_name: mariadb
    ports:
      - "0.0.0.0:3306:3306"  # Direct MySQL port
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - mariadb-network
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${DATABASE_CPUS}"
          memory: ${DATABASE_MEMORY}

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    environment:
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
    volumes:
      - ./phpmyadmin-config.php:/etc/phpmyadmin/config.inc.php:ro
    depends_on:
      - mariadb
    logging:
      driver: "none"
    networks:
      - mariadb-network
    deploy:
      resources:
        limits:
          cpus: "${PHPMYADMIN_CPUS}"
          memory: ${PHPMYADMIN_MEMORY}

networks:
  mariadb-network:
    driver: bridge
