services:
  haproxy:
    image: ${HAPROXY_IMAGE}
    container_name: galera-haproxy
    ports:
      - "0.0.0.0:${HAPROXY_MYSQL_PORT}:3306"  # Main MySQL port through HAProxy
      - "0.0.0.0:${HAPROXY_STATS_PORT}:8080"  # HAProxy stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - galera-network
    deploy:
      resources:
        limits:
          cpus: "${HAPROXY_CPUS}"
          memory: ${HAPROXY_MEMORY}

  galera-node1:
    image: ${MARIADB_IMAGE}
    container_name: galera-node1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=${GALERA_CLUSTER_NAME}
      - NODE_NAME=${NODE1_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: --wsrep-new-cluster
    volumes:
      - ./node1/data:/var/lib/mysql
      - ./node1/my.cnf:/etc/mysql/my.cnf
    networks:
      - galera-network
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${NODE_CPUS}"
          memory: ${NODE_MEMORY}

  galera-node2:
    image: ${MARIADB_IMAGE}
    container_name: galera-node2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=${GALERA_CLUSTER_NAME}
      - NODE_NAME=${NODE2_NAME}
    depends_on:
      - galera-node1
    volumes:
      - ./node2/data:/var/lib/mysql
      - ./node2/my.cnf:/etc/mysql/my.cnf
    networks:
      - galera-network
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${NODE_CPUS}"
          memory: ${NODE_MEMORY}

  galera-node3:
    image: ${MARIADB_IMAGE}
    container_name: galera-node3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=${GALERA_CLUSTER_NAME}
      - NODE_NAME=${NODE3_NAME}
    depends_on:
      - galera-node1
    volumes:
      - ./node3/data:/var/lib/mysql
      - ./node3/my.cnf:/etc/mysql/my.cnf
    networks:
      - galera-network
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${NODE_CPUS}"
          memory: ${NODE_MEMORY}

  galera-node4:
    image: ${MARIADB_IMAGE}
    container_name: galera-node4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=${GALERA_CLUSTER_NAME}
      - NODE_NAME=${NODE4_NAME}
    depends_on:
      - galera-node1
    volumes:
      - ./node4/data:/var/lib/mysql
      - ./node4/my.cnf:/etc/mysql/my.cnf
    networks:
      - galera-network
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${NODE_CPUS}"
          memory: ${NODE_MEMORY}

  phpmyadmin:
    image: ${PHPMYADMIN_IMAGE}
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
    depends_on:
      - haproxy
    logging:
      driver: "none"
    networks:
      - galera-network
    deploy:
      resources:
        limits:
          cpus: "${PHPMYADMIN_CPUS}"
          memory: ${PHPMYADMIN_MEMORY}

networks:
  galera-network:
    driver: bridge
