# Optional override: expose the database on a custom host port if set.
# To use: set DATABASE_HOST_PORT=3307 in .env or leave blank to use default port 3306.

services:
  mariadb:
    ports:
      - "${DATABASE_HOST_PORT:-}:3306"
